employe_auto_part:
    resource: "@EmployeAutoPartBundle/Controller/"
    type:     annotation
    prefix:   /employe/

client_auto_part:
    resource: "@ClientAutoPartBundle/Controller/"
    type:     annotation
    prefix:   /client/

base_auto_part:
    resource: "@BaseAutoPartBundle/Controller/"
    type:     annotation
    prefix:   /