# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
   app.connection_base:
        class: Base\AutoPartBundle\Business\Connection
   app.connection_client:
        class: Client\AutoPartBundle\Business\Connection
   app.connection_employe:
        class: Employe\AutoPartBundle\Business\Connection
   app.requete_base:
        class: Base\AutoPartBundle\Business\RequeteBdd
        arguments: ['@app.connection_base']
   app.requete_employe:
        class: Employe\AutoPartBundle\Business\RequeteBdd
        arguments: ['@app.connection_employe']
   app.requete_client:
        class: Client\AutoPartBundle\Business\RequeteBdd
        arguments: ['@app.connection_client']