# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
   connection_base:
        class: Base\AutoPartBundle\Business\Connection
   connection_client:
        class: Client\AutoPartBundle\Business\Connection
  connection_employe:
        class: Employe\AutoPartBundle\Business\Connection

  voiture_bdd:
  class: EmployeAutoPartBundle\Business\VoitureBdd
    calls:
        - [connection, ['@connection_base']]
